[package]
name = "reth-neox-node"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
# reth
reth-ethereum-engine-primitives = { workspace = true, features = ["std"] }
reth-ethereum-forks.workspace = true
reth-ethereum-primitives = { workspace = true, features = ["std"] }
reth-chain-state.workspace = true
reth-chainspec.workspace = true
reth-consensus.workspace = true
reth-engine-primitives = { workspace = true, features = ["std"] }
reth-evm.workspace = true
reth-execution-types.workspace = true
reth-neox-antimev = { workspace = true, features = ["std"] }
reth-neox-chainspec = { workspace = true, features = ["std"] }
reth-neox-consensus-engine = { workspace = true, features = ["std"] }
reth-neox-consensus = { workspace = true, features = ["std"] }
reth-neox-evm = { workspace = true, features = ["std"] }
reth-neox-network.workspace = true
reth-metrics.workspace = true
reth-network.workspace = true
reth-node-api.workspace = true
reth-node-builder.workspace = true
reth-node-ethereum.workspace = true
reth-payload-primitives.workspace = true
reth-payload-validator.workspace = true
reth-primitives-traits.workspace = true
reth-provider.workspace = true
reth-revm.workspace = true
reth-transaction-pool.workspace = true

# misc
alloy-consensus = { workspace = true, features = ["kzg"] }
alloy-eips = { workspace = true, features = ["kzg"] }
alloy-primitives = { workspace = true, features = ["k256"] }
alloy-rlp.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-sol-types.workspace = true
eyre.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["io-util", "process", "rt", "time"] }
thiserror.workspace = true
tracing.workspace = true
k256.workspace = true
libc.workspace = true
metrics.workspace = true
zeroize.workspace = true

[dev-dependencies]
aes-gcm.workspace = true
reth-provider = { workspace = true, features = ["test-utils"] }
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
sha3.workspace = true
