[package]
name = "reth-neox-antimev"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
alloy-consensus.workspace = true
alloy-primitives.workspace = true
aes = { workspace = true, features = ["zeroize"] }
aes-gcm = { workspace = true, optional = true }
blst.workspace = true
cipher.workspace = true
ctr = { workspace = true, optional = true }
k256 = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
pbkdf2 = { workspace = true, optional = true }
scrypt = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, features = ["std", "arbitrary_precision"], optional = true }
sha2.workspace = true
sha3 = { workspace = true, optional = true }
thiserror.workspace = true
subtle = { workspace = true, optional = true }
zeroize = { workspace = true, features = ["alloc"] }

[features]
default = ["std"]
std = [
    "alloy-consensus/std",
    "alloy-primitives/std",
    "dep:aes-gcm",
    "dep:k256",
    "dep:ctr",
    "dep:pbkdf2",
    "dep:rand",
    "dep:scrypt",
    "dep:serde",
    "dep:serde_json",
    "dep:sha3",
    "dep:subtle",
    "sha2/std",
]

[dev-dependencies]
tempfile.workspace = true
