[alias]
docs = "doc --workspace --all-features --no-deps"

[env]
CXXFLAGS = { value = "-D_WIN32_WINNT=0x0A00", force = false }
BINDGEN_EXTRA_CLANG_ARGS = { value = "--target=x86_64-pc-windows-gnu -mmmx", force = false }

[target.x86_64-pc-windows-gnullvm]
rustflags = [
    "-Clink-arg=-Wl,--stack,10000000",
]

[target.x86_64-pc-windows-gnu]
rustflags = [
    "-Clink-arg=-Wl,--stack,10000000",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    # Increases the stack size to 10MB, which is
    # in line with Linux (whereas default for Windows is 1MB)
    "-Clink-arg=/STACK:10000000",
]

[target.i686-pc-windows-msvc]
rustflags = [
    # Increases the stack size to 10MB, which is
    # in line with Linux (whereas default for Windows is 1MB)
    "-Clink-arg=/STACK:10000000",
]
